version: '3'
networks:
    base:
        ipam:
            driver: default
            config:
            - subnet: 172.30.0.0/24
services:
    cake_db:
        build: ./files/mysql
        networks:
            base:
                ipv4_address: '172.30.0.10'
        ports:
            - "3306:3306"
        volumes:
            - ./files/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        user: mysql
        # user: "1000:50"
        environment:
            MYSQL_DATABASE: base
            MYSQL_USER: base
            MYSQL_PASSWORD: base123
            MYSQL_ROOT_PASSWORD: root
    cake_web:
        build: ./files/web
        depends_on:
            - cake_db
        networks:
            base:
                ipv4_address: '172.30.0.100'
        ports:
            - "80:80"
        volumes:
            - ..:/var/shared
            - ../src:/var/www/html
            - ../src/local/composer.json:/var/www/html/cake/composer.json
            - ../src/local/composer.lock:/var/www/html/cake/composer.lock
            - ../src/local/config/.env:/var/www/html/cake/config/.env
            - ../src/local/config/app.php:/var/www/html/cake/config/app.php
            - ../src/local/config/bootstrap.php:/var/www/html/cake/config/bootstrap.php
        extra_hosts:
            - "dev_host:172.30.0.1"
        command: bash -c "bash /var/shared/docker/files/web/init.sh"
